### PR TITLE
Use Marques' original abstract

### PR DESCRIPTION
**Pull request by tsbockman**
In my opinion, the abstract for Luis Marques' talk is way too long given that its purpose is mostly just to help people decide whether to attend/watch.

When I [asked about this](http://forum.dlang.org/post/hhfirrgauvxzzqnjxpfq@forum.dlang.org) on the forums, Marques himself replied as follows:

> That was the "Extended Description" that I had submitted. The original "Abstract" section read:
>
> David Parnas' 1972 seminal paper, "On the criteria to be used in decomposing systems into modules", set a milestone in our collective understanding of how complex programs should be divided into more manageable parts. Over forty years later, I have reimplemented in D the example programs presented in the paper and came away with insights that are not obvious from a more casual reading of that text. In this talk I will 1) present the original insight of the paper, using more modern language; 2) relate it to current design best practices and 3) argue, with the help of my implementation, that D best fulfilled the paper's original vision, even surpassing it.

This PR uses his original abstract, instead of the extended description.

### CODE REVIEW

**Comment by tsbockman** [comment]
Is there an auto-tester that will build the website for me - like the dlang.org one - so that I can check my work?

Because I just did this all through GitHub; I haven't actually tested this yet.

**Comment by luismarques** [comment]
If you want a smaller abstract then why not include both the abstract and the extended description, then? Then you could choose either the TL;DR or the meat.

**Comment by tsbockman** [comment]
I don't know how to format that properly. The "talks" pages all seem to follow a specific layout. Suggestions?

**Comment by tsbockman** [comment]
> Suggestions?

To clarify: I'm asking for the appropriate DDOC syntax, not just what it should look like.

**Comment by andralex** [comment]
@luismarques feel free to update appropriately

**Pull request merged**
