### PR TITLE
fix grammatical error and degree name

### PR DESCRIPTION
**Pull request by joakim-noah**
Shone is the right verb here, while I presume he's applying for his master's since he's almost done with his bachelor's.

### CODE REVIEW

**Comment by joakim-noah** [comment]
@yebblies, any reason this hasn't been merged?

**Comment by yebblies** [comment]
I'll merge if Erich agrees to the changes: @ErichDonGubler

**Comment by ErichDonGubler** [comment]
@joakim-noah: Haha, a Grammar Nazi comrade! Pleased to meet you. :) I'm glad I'm not the only one who noticed after it got posted. However, UVU doesn't offer a master's -- I'll be earning that elsewhere, a location yet to be determined.

@yebblies: I say yes to "shone", but the second edit still needs modification. I'd suggest the following:

> Erich Gubler is an undergraduate student currently preparing to graduate with a Bachelor's Degree of Computer Science at Utah Valley University.

**Comment by joakim-noah** [comment]
Normally I wouldn't really care about such grammar errors, but the DConf website is a very public face of the project.

**Comment by ErichDonGubler** [comment]
@joakim-noah: Looks good. I care about it too, so I appreciate the thought. :)

**Pull request merged**
