### PR TITLE
DConf 2016 logo

### PR DESCRIPTION
**Pull request by andralex**
It doesn't look all that great so further work by experts is welcome.

### CODE REVIEW

**Comment by andralex** [comment]
(more specifically I had to change the image size)

**Comment by andralex** [comment]
Take a look: http://dconf.org/2016/index.html

**Comment by p0nce** [comment]
Hi, the font was supposed to be Droid Sans http://imgur.com/GX0HUFI
I advise to render the SVG with the font installed into some PNG of the right size (Inkscape renders beautiful PNG), then put the PNG on site else it will render differently everywhere.
Unfortunately I haven't the time to help with this.

**Comment by schuetzm** [comment]
dconf_logo_2016
dconf_logo_2016 2x

**Comment by aG0aep6G** [comment]
My take on it: #95

**Pull request closed without merging**
